#define DEBOUNCE 5
#define VIAL_KEYBOARD_UID {0xFB, 0xE6, 0x2F, 0x0B, 0x11, 0xB4, 0x9E, 0xFF}
#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 2, 3 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define DYNAMIC_KEYMAP_MACRO_COUNT 50
#define VIAL_COMBO_ENTRIES 50
#define FORCE_NKRO
#define TAPPING_TERM 200
#define OLED_BRIGHTNESS 16
